version: "2"
services:
  graphite-statsd:
    image: hopsoft/graphite-statsd:latest
    container_name: graphite-statsd
    ports:
      - "2003:2003"
    volumes:
      - "./conf/carbon.conf:/opt/graphite/conf/carbon.conf:ro"
      - "./conf/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf:ro"

  grafana-puppetserver:
    image: reidmv/grafana-puppetserver:latest
    container_name: grafana-puppetserver
    ports:
      - "3000:3000"
    links:
      - "graphite-statsd"
    build: .
